# CMake generated Testfile for 
# Source directory: D:/0.Code/OpenLPTGUI/OpenLPT
# Build directory: D:/0.Code/OpenLPTGUI/OpenLPT/build-tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_Matrix]=] "test_Matrix")
set_tests_properties([=[test_Matrix]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "failed on line" _BACKTRACE_TRIPLES "D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;16;add_test;D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;0;;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;80;include;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;0;")
add_test([=[test_myMATH]=] "test_myMATH")
set_tests_properties([=[test_myMATH]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "failed on line" _BACKTRACE_TRIPLES "D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;27;add_test;D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;0;;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;80;include;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;0;")
add_test([=[test_ImageIO]=] "test_ImageIO")
set_tests_properties([=[test_ImageIO]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "failed on line" _BACKTRACE_TRIPLES "D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;38;add_test;D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;0;;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;80;include;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;0;")
add_test([=[test_Camera]=] "test_Camera")
set_tests_properties([=[test_Camera]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "failed on line" _BACKTRACE_TRIPLES "D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;49;add_test;D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;0;;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;80;include;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;0;")
add_test([=[test_ObjectInfo]=] "test_ObjectInfo")
set_tests_properties([=[test_ObjectInfo]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "failed on line" _BACKTRACE_TRIPLES "D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;60;add_test;D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;0;;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;80;include;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;0;")
add_test([=[test_SphereInfo]=] "test_SphereInfo")
set_tests_properties([=[test_SphereInfo]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "failed on line" _BACKTRACE_TRIPLES "D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;69;add_test;D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;0;;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;80;include;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;0;")
add_test([=[test_ObjectFinder]=] "test_ObjectFinder")
set_tests_properties([=[test_ObjectFinder]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "failed on line" _BACKTRACE_TRIPLES "D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;80;add_test;D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;0;;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;80;include;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;0;")
add_test([=[test_StereoMatch]=] "test_StereoMatch")
set_tests_properties([=[test_StereoMatch]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "failed on line" _BACKTRACE_TRIPLES "D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;91;add_test;D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;0;;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;80;include;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;0;")
add_test([=[test_OTF]=] "test_OTF")
set_tests_properties([=[test_OTF]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "failed on line" _BACKTRACE_TRIPLES "D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;102;add_test;D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;0;;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;80;include;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;0;")
add_test([=[test_Shake]=] "test_Shake")
set_tests_properties([=[test_Shake]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "failed on line" _BACKTRACE_TRIPLES "D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;113;add_test;D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;0;;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;80;include;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;0;")
add_test([=[test_IPR]=] "test_IPR")
set_tests_properties([=[test_IPR]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "failed on line" _BACKTRACE_TRIPLES "D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;135;add_test;D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;0;;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;80;include;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;0;")
add_test([=[test_PredField]=] "test_PredField")
set_tests_properties([=[test_PredField]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;146;add_test;D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;0;;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;80;include;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;0;")
add_test([=[test_Track]=] "test_Track")
set_tests_properties([=[test_Track]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;155;add_test;D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;0;;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;80;include;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;0;")
add_test([=[test_STB]=] "test_STB")
set_tests_properties([=[test_STB]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;164;add_test;D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;0;;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;80;include;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;0;")
add_test([=[test_PIVChallenge]=] "test_PIVChallenge")
set_tests_properties([=[test_PIVChallenge]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;173;add_test;D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;0;;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;80;include;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;0;")
add_test([=[test_nanoflann]=] "test_nanoflann")
set_tests_properties([=[test_nanoflann]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;180;add_test;D:/0.Code/OpenLPTGUI/OpenLPT/cmake/ctest.cmake;0;;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;80;include;D:/0.Code/OpenLPTGUI/OpenLPT/CMakeLists.txt;0;")
subdirs("_deps/tiff")
